version: '3.8'

services:
  server:
    image: bloglist-backend-prod
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=mongodb+srv://admin:admin@phonebook.5zbr5hb.mongodb.net/bloglist?retryWrites=true&w=majority
        - SECRET=this_is_a_secret_value_:)
    container_name: bloglist-backend-prod
  
  app:
    image: bloglist-frontend-prod
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=/api/
    container_name: bloglist-frontend-prod
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - server